[profile.default]
src = 'src'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'base64-sol/=node_modules/base64-sol/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-contracts-08/=node_modules/openzeppelin-contracts-08/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config